idf_component_register(
  SRCS
    "main.c"
    "wifi.c"
    "wifi_ap.c"
    "settings.c"
    "ota.c"
    "log.c"
    "http_server.c"
    "matrix.cpp"
    "image_decode.c"
    "lodepng.c"
    "canvas.c"
    "kaleidoscope.c"
    "sdcard.c"
    "gallery.c"
    "font_5x7.c"
    "clock.c"
  INCLUDE_DIRS
    "."
  EMBED_TXTFILES
    "../web/app.html"
    "../web/settings.html"
  EMBED_FILES
    "../web/kaleidobox.png"
    "../web/icon-512.png"
  REQUIRES
    app_update
    bootloader_support
    driver
    esp_driver_sdmmc
    esp_http_server
    esp_netif
    esp_partition
    esp_timer
    esp_wifi
    esp-tls
    esphome__esp-hub75
    libjpeg-turbo
    fatfs
    heap
    json
    log
    lwip
    mdns
    nvs_flash
    sdmmc
)
